### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by zrd1234** [Raiden49/pure_pursuit_controller#1]
Hello, when I run, the following error occurs.
![111](https://github.com/Raiden49/pure_pursuit_controller/assets/96851901/ad630c2a-30e0-4fec-aaa9-98920643b8af)

**Comment by Raiden49** [comment]
This is because the steps you are taking to compile are incorrect. Follow the steps below to execute
1.cd catkin_ws/src/pure_pursuit_controller (Note that the directory here is within the Pure_pursuit directory, not your working directory. This means it needs to be compiled separately.)
2.cmake -B build
3.cmake --build build
4.source ./build/devel/setup.bash
5 roslaunch pure_pursuit_controller pure_pursuit_controller.launch

**Comment by zrd1234** [comment]
> This is because the steps you are taking to compile are incorrect. Follow the steps below to execute 1.cd catkin_ws/src/pure_pursuit_controller (Note that the directory here is within the Pure_pursuit directory, not your working directory. This means it needs to be compiled separately.) 2.cmake -B build 3.cmake --build build 4.source ./build/devel/setup.bash 5 roslaunch pure_pursuit_controller pure_pursuit_controller.launch

Hello, I ran it the way you did, and still reported the same error.

**Comment by Raiden49** [comment]
I've pushed new code. This time, you should only need to compile once in your working directory, and it should run

**Comment by zrd1234** [comment]
Thank you very much for your help. I can run normally now.
